// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingCertificationPlatform;

#nullable disable

namespace TrainingCertificationPlatform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520214545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassroomEquipment", b =>
                {
                    b.Property<int>("ClassroomsId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentsId")
                        .HasColumnType("int");

                    b.HasKey("ClassroomsId", "EquipmentsId");

                    b.HasIndex("EquipmentsId");

                    b.ToTable("ClassroomEquipment");

                    b.HasData(
                        new
                        {
                            ClassroomsId = 1,
                            EquipmentsId = 1
                        },
                        new
                        {
                            ClassroomsId = 1,
                            EquipmentsId = 2
                        },
                        new
                        {
                            ClassroomsId = 2,
                            EquipmentsId = 1
                        },
                        new
                        {
                            ClassroomsId = 3,
                            EquipmentsId = 3
                        },
                        new
                        {
                            ClassroomsId = 4,
                            EquipmentsId = 3
                        },
                        new
                        {
                            ClassroomsId = 5,
                            EquipmentsId = 4
                        });
                });

            modelBuilder.Entity("CourseTrack", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("TracksId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("CourseTrack");

                    b.HasData(
                        new
                        {
                            CoursesId = 1,
                            TracksId = 1
                        },
                        new
                        {
                            CoursesId = 2,
                            TracksId = 1
                        },
                        new
                        {
                            CoursesId = 3,
                            TracksId = 2
                        },
                        new
                        {
                            CoursesId = 4,
                            TracksId = 2
                        },
                        new
                        {
                            CoursesId = 5,
                            TracksId = 3
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("Assessments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CompletedBy = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CompletedBy = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 6,
                            Status = 2
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("Balances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountDue = 0m,
                            DueDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AmountDue = 60m,
                            DueDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AmountDue = 0m,
                            DueDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AmountDue = 0m,
                            DueDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 4,
                            Status = 0
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Room A",
                            Seats = 30
                        },
                        new
                        {
                            Id = 2,
                            Name = "Room B",
                            Seats = 25
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lab 1",
                            Seats = 20
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lab 2",
                            Seats = 20
                        },
                        new
                        {
                            Id = 5,
                            Name = "Conference Hall",
                            Seats = 50
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<int?>("PrerequisiteId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 25,
                            Category = 1,
                            Description = "Introduction to C# programming",
                            Duration = 20,
                            Fee = 120.0,
                            Title = "C# Basics"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            Category = 1,
                            Description = "Advanced concepts in C#",
                            Duration = 30,
                            Fee = 180.0,
                            PrerequisiteId = 1,
                            Title = "Advanced C#"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Category = 2,
                            Description = "Introduction to SQL Server",
                            Duration = 25,
                            Fee = 150.0,
                            Title = "SQL Fundamentals"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 20,
                            Category = 2,
                            Description = "Working with EF Core",
                            Duration = 20,
                            Fee = 170.0,
                            PrerequisiteId = 3,
                            Title = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 25,
                            Category = 4,
                            Description = "Introduction to networking",
                            Duration = 15,
                            Fee = 100.0,
                            Title = "Networking Basics"
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TraineeId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 1,
                            Status = 0,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 1,
                            Status = 1,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 3,
                            Status = 2,
                            TraineeId = 6
                        },
                        new
                        {
                            Id = 4,
                            CompletionDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 4,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 2,
                            Status = 4,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 6,
                            CompletionDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 5,
                            Status = 3,
                            TraineeId = 6
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Projector"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Whiteboard"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lab Computers"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Networking Kit"
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.InstructorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayEnd")
                        .HasColumnType("int");

                    b.Property<int>("DayStart")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayEnd = 4,
                            DayStart = 0,
                            EndTime = new TimeOnly(16, 0, 0),
                            InstructorId = 2,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayEnd = 4,
                            DayStart = 0,
                            EndTime = new TimeOnly(17, 0, 0),
                            InstructorId = 5,
                            StartTime = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.InstructorExpertise", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("InstructorExpertises");

                    b.HasData(
                        new
                        {
                            InstructorId = 2,
                            CourseId = 1
                        },
                        new
                        {
                            InstructorId = 2,
                            CourseId = 2
                        },
                        new
                        {
                            InstructorId = 2,
                            CourseId = 5
                        },
                        new
                        {
                            InstructorId = 5,
                            CourseId = 3
                        },
                        new
                        {
                            InstructorId = 5,
                            CourseId = 4
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Welcome to the platform",
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "New session assigned",
                            Status = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Payment reminder",
                            Status = 0,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 120m,
                            EnrollmentId = 1,
                            PaymentDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 60m,
                            EnrollmentId = 2,
                            PaymentDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 150m,
                            EnrollmentId = 3,
                            PaymentDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 180m,
                            EnrollmentId = 4,
                            PaymentDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 170m,
                            EnrollmentId = 5,
                            PaymentDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ClassroomId", "SessionDate");

                    b.HasIndex("InstructorId", "SessionDate");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 1,
                            CourseId = 1,
                            EndTime = new TimeOnly(11, 0, 0),
                            InstructorId = 2,
                            SessionDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 2,
                            CourseId = 2,
                            EndTime = new TimeOnly(14, 0, 0),
                            InstructorId = 2,
                            SessionDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 3,
                            CourseId = 3,
                            EndTime = new TimeOnly(12, 0, 0),
                            InstructorId = 5,
                            SessionDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            ClassroomId = 4,
                            CourseId = 4,
                            EndTime = new TimeOnly(15, 0, 0),
                            InstructorId = 5,
                            SessionDate = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            ClassroomId = 5,
                            CourseId = 5,
                            EndTime = new TimeOnly(16, 0, 0),
                            InstructorId = 2,
                            SessionDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(14, 0, 0)
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Backend programming track",
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Database management track",
                            Name = "Database Administration"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Networking certification track",
                            Name = "Networking Essentials"
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.TraineeCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("TraineeId");

                    b.ToTable("TraineeCertifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificateReferenceNumber = "CERT-1001",
                            Status = 1,
                            TrackId = 1,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CertificateReferenceNumber = "CERT-1002",
                            Status = 1,
                            TrackId = 2,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 3,
                            CertificateReferenceNumber = "",
                            Status = 0,
                            TrackId = 3,
                            TraineeId = 6
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPR = "123456789",
                            Email = "ali@mail.com",
                            FirstName = "Ali",
                            LastName = "Ahmad",
                            Password = "$2a$12$ZPzIhfjkDv3uc/4fEkhAfuAM/hYixvISLMEhyBYk7dxrsGJdw15Rq",
                            Phone = "99999991",
                            RegistrationDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            CPR = "098765432",
                            Email = "omar@mail.com",
                            FirstName = "Omar",
                            LastName = "Ali",
                            Password = "$2a$12$ZPzIhfjkDv3uc/4fEkhAfuAM/hYixvISLMEhyBYk7dxrsGJdw15Rq",
                            Phone = "99999994",
                            RegistrationDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            CPR = "444555666",
                            Email = "mariam@mail.com",
                            FirstName = "Mariam",
                            LastName = "Hasan",
                            Password = "$2a$12$ZPzIhfjkDv3uc/4fEkhAfuAM/hYixvISLMEhyBYk7dxrsGJdw15Rq",
                            Phone = "99999996",
                            RegistrationDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            CPR = "987654321",
                            Email = "sara@mail.com",
                            FirstName = "Sara",
                            LastName = "Mohamed",
                            Password = "$2a$12$ZPzIhfjkDv3uc/4fEkhAfuAM/hYixvISLMEhyBYk7dxrsGJdw15Rq",
                            Phone = "99999992",
                            RegistrationDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            CPR = "012345678",
                            Email = "fatima@mail.com",
                            FirstName = "Fatima",
                            LastName = "Yousef",
                            Password = "$2a$12$ZPzIhfjkDv3uc/4fEkhAfuAM/hYixvISLMEhyBYk7dxrsGJdw15Rq",
                            Phone = "99999995",
                            RegistrationDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CPR = "112233445",
                            Email = "dana@mail.com",
                            FirstName = "Dana",
                            LastName = "Albanki",
                            Password = "$2a$12$ZPzIhfjkDv3uc/4fEkhAfuAM/hYixvISLMEhyBYk7dxrsGJdw15Rq",
                            Phone = "99999993",
                            RegistrationDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 2
                        });
                });

            modelBuilder.Entity("ClassroomEquipment", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTrack", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Assessment", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Enrollment", "Enrollment")
                        .WithOne()
                        .HasForeignKey("TrainingCertificationPlatform.Models.Assessment", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Balance", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Enrollment", "Enrollment")
                        .WithOne("Balance")
                        .HasForeignKey("TrainingCertificationPlatform.Models.Balance", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Course", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Course", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteId");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Enrollment", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId");

                    b.Navigation("Session");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.InstructorAvailability", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.InstructorExpertise", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Course", "Course")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Instructor")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Notification", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Payment", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Session", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.TraineeCertification", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Course", b =>
                {
                    b.Navigation("InstructorExpertises");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Enrollment", b =>
                {
                    b.Navigation("Balance");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("InstructorExpertises");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
