// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingCertificationPlatform;

#nullable disable

namespace TrainingCertificationPlatform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassroomEquipment", b =>
                {
                    b.Property<int>("ClassroomsId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentsId")
                        .HasColumnType("int");

                    b.HasKey("ClassroomsId", "EquipmentsId");

                    b.HasIndex("EquipmentsId");

                    b.ToTable("ClassroomEquipment");

                    b.HasData(
                        new
                        {
                            ClassroomsId = 1,
                            EquipmentsId = 1
                        },
                        new
                        {
                            ClassroomsId = 1,
                            EquipmentsId = 3
                        },
                        new
                        {
                            ClassroomsId = 2,
                            EquipmentsId = 2
                        },
                        new
                        {
                            ClassroomsId = 2,
                            EquipmentsId = 1
                        },
                        new
                        {
                            ClassroomsId = 3,
                            EquipmentsId = 1
                        },
                        new
                        {
                            ClassroomsId = 3,
                            EquipmentsId = 3
                        });
                });

            modelBuilder.Entity("CourseTrack", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("TracksId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("CourseTrack");

                    b.HasData(
                        new
                        {
                            CoursesId = 1,
                            TracksId = 1
                        },
                        new
                        {
                            CoursesId = 2,
                            TracksId = 1
                        },
                        new
                        {
                            CoursesId = 3,
                            TracksId = 1
                        },
                        new
                        {
                            CoursesId = 4,
                            TracksId = 2
                        },
                        new
                        {
                            CoursesId = 5,
                            TracksId = 2
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("Assessments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedBy = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CompletedBy = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CompletedBy = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CompletedBy = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CompletedBy = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CompletedBy = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            DueDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 8,
                            Status = 0
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("Balances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountDue = 0m,
                            DueDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AmountDue = 0m,
                            DueDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AmountDue = 0m,
                            DueDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AmountDue = 0m,
                            DueDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AmountDue = 0m,
                            DueDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            AmountDue = 70m,
                            DueDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            AmountDue = 0m,
                            DueDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            AmountDue = 90m,
                            DueDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 8,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            AmountDue = 90m,
                            DueDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentId = 9,
                            Status = 2
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Room A101",
                            Seats = 20
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lab B202",
                            Seats = 15
                        },
                        new
                        {
                            Id = 3,
                            Name = "Room C303",
                            Seats = 25
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<int?>("PrerequisiteId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 15,
                            Category = 1,
                            Description = "Core concepts of C# programming including variables, control flow, and OOP.",
                            Duration = 20,
                            Fee = 120.0,
                            Title = "C# Fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 12,
                            Category = 1,
                            Description = "Deep dive into LINQ, async/await, generics, and design patterns.",
                            Duration = 30,
                            Fee = 180.0,
                            PrerequisiteId = 1,
                            Title = "Advanced C# & .NET"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 12,
                            Category = 3,
                            Description = "Building web applications using ASP.NET Core MVC and Entity Framework.",
                            Duration = 35,
                            Fee = 200.0,
                            PrerequisiteId = 2,
                            Title = "ASP.NET Core MVC"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 15,
                            Category = 2,
                            Description = "Introduction to relational databases, T-SQL queries, and SQL Server.",
                            Duration = 25,
                            Fee = 150.0,
                            Title = "SQL Server Fundamentals"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 12,
                            Category = 2,
                            Description = "Stored procedures, indexing, query optimization, and database design.",
                            Duration = 30,
                            Fee = 175.0,
                            PrerequisiteId = 4,
                            Title = "Advanced SQL & Performance"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 20,
                            Category = 5,
                            Description = "Common vulnerabilities, OWASP Top 10, secure coding practices.",
                            Duration = 20,
                            Fee = 140.0,
                            Title = "Web Security Essentials"
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TraineeId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletionDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 1,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompletionDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 2,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompletionDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 3,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompletionDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 4,
                            Status = 3,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 5,
                            CompletionDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 5,
                            Status = 3,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 6,
                            EnrollmentDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 6,
                            Status = 0,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 7,
                            CompletionDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 1,
                            Status = 3,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 8,
                            EnrollmentDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 2,
                            Status = 2,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 9,
                            EnrollmentDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionId = 4,
                            Status = 4,
                            TraineeId = 3
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Projector"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lab Computers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Whiteboard"
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ContentRating")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorRating")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationRating")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<bool>("RecommendCourse")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Sara explains concepts very clearly. Highly recommended.",
                            ContentRating = 5,
                            CourseId = 1,
                            InstructorId = 4,
                            InstructorRating = 5,
                            OrganizationRating = 4,
                            Rating = 5,
                            RecommendCourse = true,
                            SubmittedAt = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Hassan is a great instructor. The hands-on labs were very helpful.",
                            ContentRating = 4,
                            CourseId = 4,
                            InstructorId = 5,
                            InstructorRating = 5,
                            OrganizationRating = 5,
                            Rating = 5,
                            RecommendCourse = true,
                            SubmittedAt = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Good introduction. Would have liked more exercises.",
                            ContentRating = 4,
                            CourseId = 1,
                            InstructorId = 4,
                            InstructorRating = 4,
                            OrganizationRating = 3,
                            Rating = 4,
                            RecommendCourse = true,
                            SubmittedAt = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeId = 3
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.InstructorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayEnd")
                        .HasColumnType("int");

                    b.Property<int>("DayStart")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayEnd = 4,
                            DayStart = 0,
                            EndTime = new TimeOnly(16, 0, 0),
                            InstructorId = 4,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayEnd = 3,
                            DayStart = 0,
                            EndTime = new TimeOnly(17, 0, 0),
                            InstructorId = 5,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DayEnd = 4,
                            DayStart = 1,
                            EndTime = new TimeOnly(18, 0, 0),
                            InstructorId = 6,
                            StartTime = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.InstructorExpertise", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("InstructorExpertises");

                    b.HasData(
                        new
                        {
                            InstructorId = 4,
                            CourseId = 1
                        },
                        new
                        {
                            InstructorId = 4,
                            CourseId = 2
                        },
                        new
                        {
                            InstructorId = 4,
                            CourseId = 3
                        },
                        new
                        {
                            InstructorId = 5,
                            CourseId = 4
                        },
                        new
                        {
                            InstructorId = 5,
                            CourseId = 5
                        },
                        new
                        {
                            InstructorId = 6,
                            CourseId = 6
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Welcome to the Training Platform, Ahmed!",
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Welcome to the Training Platform, Fatima!",
                            Status = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Welcome to the Training Platform, Khalid!",
                            Status = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Your enrollment in C# Fundamentals has been confirmed.",
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Congratulations! You have completed the Full-Stack .NET Developer track.",
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Your enrollment in SQL Server Fundamentals has been confirmed.",
                            Status = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Reminder: Your balance for Web Security is pending.",
                            Status = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Reminder: Your balance for Advanced C# is overdue.",
                            Status = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "You have 3 sessions scheduled this month.",
                            Status = 0,
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "You have 2 sessions scheduled this month.",
                            Status = 0,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 120m,
                            EnrollmentId = 1,
                            PaymentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 180m,
                            EnrollmentId = 2,
                            PaymentDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 200m,
                            EnrollmentId = 3,
                            PaymentDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 150m,
                            EnrollmentId = 4,
                            PaymentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 175m,
                            EnrollmentId = 5,
                            PaymentDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 70m,
                            EnrollmentId = 6,
                            PaymentDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Amount = 120m,
                            EnrollmentId = 7,
                            PaymentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 90m,
                            EnrollmentId = 8,
                            PaymentDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            Amount = 60m,
                            EnrollmentId = 9,
                            PaymentDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ClassroomId", "SessionDate");

                    b.HasIndex("InstructorId", "SessionDate");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 1,
                            CourseId = 1,
                            EndTime = new TimeOnly(12, 0, 0),
                            InstructorId = 4,
                            SessionDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 2,
                            CourseId = 2,
                            EndTime = new TimeOnly(12, 0, 0),
                            InstructorId = 4,
                            SessionDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 2,
                            CourseId = 3,
                            EndTime = new TimeOnly(12, 0, 0),
                            InstructorId = 4,
                            SessionDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            ClassroomId = 3,
                            CourseId = 4,
                            EndTime = new TimeOnly(13, 0, 0),
                            InstructorId = 5,
                            SessionDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            ClassroomId = 3,
                            CourseId = 5,
                            EndTime = new TimeOnly(13, 0, 0),
                            InstructorId = 5,
                            SessionDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            ClassroomId = 1,
                            CourseId = 6,
                            EndTime = new TimeOnly(13, 0, 0),
                            InstructorId = 6,
                            SessionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Covers C#, Advanced C#, and ASP.NET Core MVC to build complete web applications.",
                            Name = "Full-Stack .NET Developer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Covers SQL fundamentals and advanced SQL for database management and optimization.",
                            Name = "Database Administrator"
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.TraineeCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("TraineeId");

                    b.ToTable("TraineeCertifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificateReferenceNumber = "CERT-NET-2026-001",
                            Status = 1,
                            TrackId = 1,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CertificateReferenceNumber = "CERT-DBA-2026-001",
                            Status = 1,
                            TrackId = 2,
                            TraineeId = 2
                        });
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPR = "860412345",
                            Email = "ahmed@mail.com",
                            FirstName = "Ahmed",
                            LastName = "AlMansouri",
                            Password = "$2a$12$Ys7YXxI9M7EqQY60T8aNFe31SwSs8IGXjfAYsFNp55NcGyzL4cIym",
                            Phone = "39001001",
                            RegistrationDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            CPR = "920815678",
                            Email = "fatima@mail.com",
                            FirstName = "Fatima",
                            LastName = "Ali",
                            Password = "$2a$12$Ys7YXxI9M7EqQY60T8aNFe31SwSs8IGXjfAYsFNp55NcGyzL4cIym",
                            Phone = "39001002",
                            RegistrationDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            CPR = "950322901",
                            Email = "khalid@mail.com",
                            FirstName = "Khalid",
                            LastName = "AlDosari",
                            Password = "$2a$12$Ys7YXxI9M7EqQY60T8aNFe31SwSs8IGXjfAYsFNp55NcGyzL4cIym",
                            Phone = "39001003",
                            RegistrationDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            CPR = "780610234",
                            Email = "sara@mail.com",
                            FirstName = "Sara",
                            LastName = "AlZayani",
                            Password = "$2a$12$Ys7YXxI9M7EqQY60T8aNFe31SwSs8IGXjfAYsFNp55NcGyzL4cIym",
                            Phone = "39002001",
                            RegistrationDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            CPR = "820905567",
                            Email = "hassan@mail.com",
                            FirstName = "Hassan",
                            LastName = "Ali",
                            Password = "$2a$12$Ys7YXxI9M7EqQY60T8aNFe31SwSs8IGXjfAYsFNp55NcGyzL4cIym",
                            Phone = "39002002",
                            RegistrationDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            CPR = "750318890",
                            Email = "noor@mail.com",
                            FirstName = "Noor",
                            LastName = "AlHammadi",
                            Password = "$2a$12$Ys7YXxI9M7EqQY60T8aNFe31SwSs8IGXjfAYsFNp55NcGyzL4cIym",
                            Phone = "39002003",
                            RegistrationDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            CPR = "810724112",
                            Email = "dana@mail.com",
                            FirstName = "Dana",
                            LastName = "AlBanki",
                            Password = "$2a$12$Ys7YXxI9M7EqQY60T8aNFe31SwSs8IGXjfAYsFNp55NcGyzL4cIym",
                            Phone = "39003001",
                            RegistrationDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 2
                        });
                });

            modelBuilder.Entity("ClassroomEquipment", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Classroom", null)
                        .WithMany()
                        .HasForeignKey("ClassroomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTrack", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Assessment", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Enrollment", "Enrollment")
                        .WithOne()
                        .HasForeignKey("TrainingCertificationPlatform.Models.Assessment", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Balance", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Enrollment", "Enrollment")
                        .WithOne("Balance")
                        .HasForeignKey("TrainingCertificationPlatform.Models.Balance", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Course", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Course", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteId");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Enrollment", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId");

                    b.Navigation("Session");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Feedback", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Course", "Course")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Instructor")
                        .WithMany("ReceivedFeedbacks")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Trainee")
                        .WithMany("GivenFeedbacks")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.InstructorAvailability", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.InstructorExpertise", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Course", "Course")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Instructor")
                        .WithMany("InstructorExpertises")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Notification", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Payment", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Session", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.TraineeCertification", b =>
                {
                    b.HasOne("TrainingCertificationPlatform.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCertificationPlatform.Models.User", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Course", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("InstructorExpertises");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.Enrollment", b =>
                {
                    b.Navigation("Balance");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TrainingCertificationPlatform.Models.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("GivenFeedbacks");

                    b.Navigation("InstructorExpertises");

                    b.Navigation("Notifications");

                    b.Navigation("ReceivedFeedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
